"""add audits.report_html

Revision ID: 163af19ce3e5
Revises: 794eb0bdfb50
Create Date: 2026-06-29 09:00:42.215007
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163af19ce3e5'
down_revision: Union[str, None] = '794eb0bdfb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('report_html')

    # ### end Alembic commands ###
