"""add audits.parent_audit_id

Revision ID: 4c40bbc1e5ae
Revises: d1fce41e0836
Create Date: 2026-07-02 07:43:17.112312
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c40bbc1e5ae'
down_revision: Union[str, None] = 'd1fce41e0836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Named FK (not autogenerated None) so the SQLite batch downgrade can
    # drop it by name.
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_audit_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_audits_parent_audit_id'), ['parent_audit_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_audits_parent_audit_id', 'audits',
            ['parent_audit_id'], ['id'], ondelete='CASCADE',
        )


def downgrade() -> None:
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audits_parent_audit_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audits_parent_audit_id'))
        batch_op.drop_column('parent_audit_id')
