"""initial schema: clients, audits, audit_findings

Revision ID: 709993b73e6b
Revises: 
Create Date: 2026-06-27 08:03:58.226111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709993b73e6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('render_js', sa.Boolean(), nullable=False),
    sa.Column('rendered_with', sa.String(length=32), nullable=True),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=2), nullable=True),
    sa.Column('ai_visibility_score', sa.Float(), nullable=True),
    sa.Column('site_aggregate_score', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audits_client_id', 'audits', ['client_id'])
    op.create_index('ix_audits_created_at', 'audits', ['created_at'])
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('category_key', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_findings_audit_id', 'audit_findings', ['audit_id'])
    op.create_index(
        'ix_audit_findings_category_key', 'audit_findings', ['category_key']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_findings_category_key', table_name='audit_findings')
    op.drop_index('ix_audit_findings_audit_id', table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index('ix_audits_created_at', table_name='audits')
    op.drop_index('ix_audits_client_id', table_name='audits')
    op.drop_table('audits')
    op.drop_table('clients')
    # ### end Alembic commands ###
