"""add audits.overrides

Revision ID: d1fce41e0836
Revises: 163af19ce3e5
Create Date: 2026-07-02 06:17:55.918017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fce41e0836'
down_revision: Union[str, None] = '163af19ce3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overrides', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audits', schema=None) as batch_op:
        batch_op.drop_column('overrides')

    # ### end Alembic commands ###
